/**
 * Worker Workflow
 *
 * Executes a single task for an agent using Cloudflare Workflows.
 * This workflow handles the complete lifecycle of a task:
 * 1. Load task and agent context
 * 2. Check for physical barriers
 * 3. Plan the work using AI
 * 4. Execute each step
 * 5. Log progress and complete
 */

import { WorkflowEntrypoint, WorkflowEvent, WorkflowStep } from 'cloudflare:workers';
import {
  PhysicalBarrier,
  detectPhysicalBarrier,
  createHumanTask,
  notifyHumans,
} from '../lib/physical-barrier';

// ============================================================================
// Types
// ============================================================================

/**
 * Payload passed when triggering the workflow
 */
export interface WorkerPayload {
  taskId: string;
  agentId: string;
}

/**
 * Environment bindings for Cloudflare Workers
 */
export interface Env {
  DB: D1Database;
  // AI binding removed - using distributed compute network instead
}

/**
 * Task from the database
 */
interface Task {
  id: string;
  project_id: string;
  title: string;
  description: string | null;
  status: string;
  priority: number;
  assigned_agent: string | null;
  blocked_by: string | null;
  requires_physical: number; // 0 or 1 in SQLite
  progress: number;
  result: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Agent state from the database (raw JSON strings)
 */
interface AgentStateRaw {
  agent_id: string;
  project_id: string;
  persona: string; // JSON string
  memory: string | null; // JSON string
  current_task_id: string | null;
  status: string;
  tokens_used: number;
  last_active: string | null;
  created_at: string;
}

/**
 * Agent persona defining behavior and specialization
 */
interface AgentPersona {
  name: string;
  role: string;
  model: string;
  specializations: string[];
  system_prompt: string;
}

/**
 * Agent memory for context and learnings
 */
interface AgentMemory {
  context: string[];
  learnings: string[];
}

/**
 * Serializable context for workflow steps
 */
interface SerializableContext {
  task: Task;
  agentId: string;
  projectId: string;
  persona: AgentPersona;
  memory: AgentMemory;
  projectName: string;
  projectSlug: string;
}

/**
 * A single step in the execution plan
 */
interface PlanStep {
  id: string;
  action: string;
  description: string;
  inputs: string; // JSON string for serialization
  expectedOutput: string;
}

/**
 * Execution plan generated by AI (serializable)
 */
interface ExecutionPlan {
  steps: PlanStep[];
  estimatedDuration: string;
}

/**
 * Result from executing a single step (serializable)
 */
interface StepResult {
  success: boolean;
  output: string; // JSON string for serialization
  needsPhysical: boolean;
  blockReason: string | null;
  tokensUsed: number;
  durationMs: number;
}

/**
 * Final workflow result
 */
interface WorkflowResult {
  status: 'completed' | 'blocked' | 'failed';
  reason: string | null;
  partial: boolean;
  resultsJson: string | null; // JSON string for serialization
}

// ============================================================================
// Prompts
// ============================================================================

/**
 * Prompt for AI to plan task execution
 */
export const TASK_PLANNING_PROMPT = `You are an AI agent planner. Your job is to break down a task into executable steps.

CONTEXT:
- Agent Role: {{agentRole}}
- Agent Specializations: {{agentSpecializations}}
- Task Title: {{taskTitle}}
- Task Description: {{taskDescription}}

RULES:
1. Each step should be atomic and independently verifiable
2. Steps should be ordered by dependency (prerequisites first)
3. Identify any steps that require physical action (ordering parts, assembly, testing hardware)
4. Each step must have a clear expected output
5. Keep the plan focused and efficient - minimize unnecessary steps

OUTPUT FORMAT (JSON):
{
  "steps": [
    {
      "id": "step_1",
      "action": "research|code|analyze|design|document|physical",
      "description": "Clear description of what to do",
      "inputs": "{}",
      "expectedOutput": "What this step produces"
    }
  ],
  "estimatedDuration": "e.g., 30 minutes",
  "physicalStepsIdentified": ["step_id_1", "step_id_2"]
}

Respond with ONLY the JSON, no additional text.`;

/**
 * Prompt for AI to execute a single step
 */
export const TASK_EXECUTION_PROMPT = `You are an AI agent executing a specific task step.

CONTEXT:
- Agent Role: {{agentRole}}
- Agent Specializations: {{agentSpecializations}}
- Overall Task: {{taskTitle}}
- Current Step: {{stepDescription}}
- Step Action Type: {{stepAction}}
- Step Inputs: {{stepInputs}}
- Expected Output: {{expectedOutput}}

AGENT MEMORY (previous learnings):
{{agentMemory}}

INSTRUCTIONS:
1. Execute the step according to its action type
2. For "research" - gather and synthesize information
3. For "code" - generate clean, well-documented code
4. For "analyze" - provide structured analysis
5. For "design" - create specifications or diagrams
6. For "document" - write clear documentation
7. If you discover this step requires physical action, indicate this clearly

OUTPUT FORMAT (JSON):
{
  "success": true,
  "output": "The actual result of the step (code, analysis, research, etc.)",
  "artifacts": [
    {
      "type": "code|research_note|design|bom",
      "name": "artifact name",
      "content": "artifact content"
    }
  ],
  "needsPhysical": false,
  "blockReason": null,
  "insights": ["Any new learnings to remember"]
}

Respond with ONLY the JSON, no additional text.`;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Generates a unique ID with a prefix
 */
function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
}

/**
 * Replaces template placeholders in a prompt
 */
function fillPromptTemplate(
  template: string,
  values: { [key: string]: string }
): string {
  let result = template;
  for (const [key, value] of Object.entries(values)) {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
  }
  return result;
}

/**
 * Safely parses JSON from AI response, handling common issues
 */
function safeParseJson<T>(text: string): T | null {
  try {
    // Try direct parse first
    return JSON.parse(text) as T;
  } catch {
    // Try to extract JSON from markdown code blocks
    const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
    if (jsonMatch) {
      try {
        return JSON.parse(jsonMatch[1].trim()) as T;
      } catch {
        return null;
      }
    }
    // Try to find JSON object in response
    const objectMatch = text.match(/\{[\s\S]*\}/);
    if (objectMatch) {
      try {
        return JSON.parse(objectMatch[0]) as T;
      } catch {
        return null;
      }
    }
    return null;
  }
}

/**
 * Rough token estimation (4 chars per token average)
 */
function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

// ============================================================================
// Worker Workflow
// ============================================================================

/**
 * WorkerWorkflow executes a single task for an agent.
 *
 * This workflow is triggered by the Manager Workflow or manually via API.
 * It handles the complete lifecycle of task execution including:
 * - Loading context from the database
 * - Checking for physical barriers
 * - Planning work using AI
 * - Executing each step
 * - Logging all work
 * - Creating artifacts
 */
export class WorkerWorkflow extends WorkflowEntrypoint<Env, WorkerPayload> {
  /**
   * Main workflow execution
   */
  async run(
    event: WorkflowEvent<WorkerPayload>,
    step: WorkflowStep
  ): Promise<WorkflowResult> {
    const { taskId, agentId } = event.payload;

    console.log(`WorkerWorkflow started: task=${taskId}, agent=${agentId}`);

    // Step 1: Load context from database
    const context = await step.do('load-context', async () => {
      return await this.loadContext(taskId, agentId);
    });

    if (!context) {
      console.error(`Failed to load context for task=${taskId}, agent=${agentId}`);
      // Reset agent to idle so it's not stuck as 'working'
      await step.do('cleanup-agent-on-context-fail', async () => {
        await this.updateAgentStatus(agentId, 'idle', null);
        return { cleaned: true };
      });
      return { status: 'failed', reason: 'context_not_found', partial: false, resultsJson: null };
    }

    // Update agent status to working
    await step.do('update-agent-status', async () => {
      await this.updateAgentStatus(agentId, 'working', taskId);
      return { updated: true };
    });

    // Step 2: Check for physical barrier
    if (context.task.requires_physical === 1) {
      const blockResult = await step.do('handle-physical', async () => {
        // Create physical barrier record
        const barrier: PhysicalBarrier = {
          type: 'test', // Default type, could be determined from task description
          description: context.task.description || context.task.title,
          instructions: [
            `Complete the following physical task:`,
            context.task.title,
            context.task.description || '',
          ],
          blocking_tasks: [taskId],
        };

        // Mark task as blocked
        await this.markTaskBlocked(taskId, 'Requires physical action');

        // Notify humans
        await notifyHumans(barrier);

        // Update agent status back to idle
        await this.updateAgentStatus(agentId, 'idle', null);

        return { blocked: true, reason: 'physical_required' };
      });

      return { status: 'blocked', reason: blockResult.reason, partial: false, resultsJson: null };
    }

    // Step 3: Plan the work using AI
    const plan = await step.do('plan-work', async () => {
      return await this.planWork(context);
    });

    if (!plan || !plan.steps || plan.steps.length === 0) {
      console.error(`Failed to create execution plan for task=${taskId}`);
      // Reset agent to idle so it's not stuck as 'working'
      await step.do('cleanup-agent-on-plan-fail', async () => {
        await this.updateAgentStatus(agentId, 'idle', null);
        return { cleaned: true };
      });
      return { status: 'failed', reason: 'planning_failed', partial: false, resultsJson: null };
    }

    console.log(
      `Execution plan created with ${plan.steps.length} steps for task=${taskId}`
    );

    // Initialize results accumulator
    const allResults: { [stepId: string]: string } = {};

    // Step 4: Execute each step in the plan
    for (let i = 0; i < plan.steps.length; i++) {
      const planStep = plan.steps[i];

      // Update task progress
      const progress = Math.round(((i + 1) / plan.steps.length) * 100);
      await step.do(`progress-${planStep.id}`, async () => {
        await this.updateTaskProgress(taskId, progress);
        return { progress };
      });

      // Execute the step
      const result = await step.do(`exec-${planStep.id}`, async () => {
        return await this.executeStep(planStep, context);
      });

      // Log the work
      await step.do(`log-${planStep.id}`, async () => {
        await this.logWork(
          agentId,
          taskId,
          planStep.action,
          JSON.stringify({ step: planStep }),
          result.output,
          result.durationMs,
          result.tokensUsed
        );
        return { logged: true };
      });

      // Store result
      allResults[planStep.id] = result.output;

      // Check if we hit a physical barrier mid-execution
      if (result.needsPhysical) {
        await step.do('mid-physical-barrier', async () => {
          // Detect and create the physical barrier
          const barrier = detectPhysicalBarrier(
            result.blockReason || planStep.description
          );

          if (barrier) {
            barrier.blocking_tasks = [taskId];
            await createHumanTask(barrier, context.projectId, this.env.DB);
            await notifyHumans(barrier);
          }

          // Mark task as blocked
          await this.markTaskBlocked(
            taskId,
            result.blockReason || 'Physical action required during execution'
          );

          // Update agent status back to idle
          await this.updateAgentStatus(agentId, 'idle', null);

          return { blocked: true };
        });

        return {
          status: 'blocked',
          reason: result.blockReason,
          partial: true,
          resultsJson: JSON.stringify(allResults),
        };
      }

      // Check if step failed
      if (!result.success) {
        console.error(`Step ${planStep.id} failed for task=${taskId}`);
        // Continue with remaining steps if possible
      }
    }

    // Step 5: Create any artifacts
    await step.do('create-artifacts', async () => {
      // Artifacts would be extracted from step results
      // For now, create a summary artifact
      await this.createArtifact(
        taskId,
        'research_note',
        `${context.task.title} - Summary`,
        JSON.stringify(allResults, null, 2)
      );
      return { created: true };
    });

    // Step 6: Complete the task
    await step.do('complete', async () => {
      // Update task status to completed
      await this.completeTask(taskId, JSON.stringify(allResults));

      // Update agent state
      await this.updateAgentStatus(agentId, 'idle', null);

      // Update agent memory with any learnings
      await this.updateAgentMemory(agentId, context);

      return { completed: true };
    });

    console.log(`WorkerWorkflow completed: task=${taskId}`);

    return { status: 'completed', reason: null, partial: false, resultsJson: JSON.stringify(allResults) };
  }

  // ==========================================================================
  // Database Operations
  // ==========================================================================

  /**
   * Loads task, agent, and project context from the database
   */
  private async loadContext(
    taskId: string,
    agentId: string
  ): Promise<SerializableContext | null> {
    try {
      // Get task
      const taskResult = await this.env.DB.prepare(
        'SELECT * FROM tasks WHERE id = ?'
      )
        .bind(taskId)
        .first<Task>();

      if (!taskResult) {
        console.error(`Task not found: ${taskId}`);
        return null;
      }

      // Get agent
      const agentResult = await this.env.DB.prepare(
        'SELECT * FROM agent_state WHERE agent_id = ?'
      )
        .bind(agentId)
        .first<AgentStateRaw>();

      if (!agentResult) {
        console.error(`Agent not found: ${agentId}`);
        return null;
      }

      // Parse JSON fields with defaults
      const persona: AgentPersona = safeParseJson<AgentPersona>(agentResult.persona) || {
        name: agentId,
        role: 'Worker',
        model: '@cf/meta/llama-3.1-70b-instruct',
        specializations: [],
        system_prompt: 'You are a helpful AI agent.',
      };

      const memory: AgentMemory = safeParseJson<AgentMemory>(agentResult.memory || '{}') || {
        context: [],
        learnings: [],
      };

      // Get project
      const projectResult = await this.env.DB.prepare(
        'SELECT id, name, slug FROM projects WHERE id = ?'
      )
        .bind(taskResult.project_id)
        .first<{ id: string; name: string; slug: string }>();

      if (!projectResult) {
        console.error(`Project not found: ${taskResult.project_id}`);
        return null;
      }

      return {
        task: taskResult,
        agentId: agentResult.agent_id,
        projectId: agentResult.project_id,
        persona,
        memory,
        projectName: projectResult.name,
        projectSlug: projectResult.slug,
      };
    } catch (error) {
      console.error('Failed to load context:', error);
      return null;
    }
  }

  /**
   * Updates the agent status and current task
   */
  private async updateAgentStatus(
    agentId: string,
    status: string,
    currentTaskId: string | null
  ): Promise<void> {
    await this.env.DB.prepare(
      `UPDATE agent_state
       SET status = ?, current_task_id = ?, last_active = datetime('now')
       WHERE agent_id = ?`
    )
      .bind(status, currentTaskId, agentId)
      .run();
  }

  /**
   * Updates the task progress percentage
   */
  private async updateTaskProgress(
    taskId: string,
    progress: number
  ): Promise<void> {
    await this.env.DB.prepare(
      `UPDATE tasks
       SET progress = ?, status = 'in_progress', updated_at = datetime('now')
       WHERE id = ?`
    )
      .bind(progress, taskId)
      .run();
  }

  /**
   * Marks a task as blocked
   */
  private async markTaskBlocked(
    taskId: string,
    reason: string
  ): Promise<void> {
    await this.env.DB.prepare(
      `UPDATE tasks
       SET status = 'blocked',
           result = ?,
           updated_at = datetime('now')
       WHERE id = ?`
    )
      .bind(JSON.stringify({ blocked_reason: reason }), taskId)
      .run();
  }

  /**
   * Marks a task as completed
   */
  private async completeTask(
    taskId: string,
    resultsJson: string
  ): Promise<void> {
    await this.env.DB.prepare(
      `UPDATE tasks
       SET status = 'completed',
           progress = 100,
           result = ?,
           updated_at = datetime('now')
       WHERE id = ?`
    )
      .bind(resultsJson, taskId)
      .run();
  }

  /**
   * Logs work to the work_log table
   */
  private async logWork(
    agentId: string,
    taskId: string,
    action: string,
    inputJson: string,
    outputJson: string,
    durationMs: number,
    tokensUsed: number
  ): Promise<void> {
    const logId = generateId('log');

    await this.env.DB.prepare(
      `INSERT INTO work_log (id, agent_id, task_id, action, input, output, duration_ms, tokens_used, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))`
    )
      .bind(
        logId,
        agentId,
        taskId,
        action,
        inputJson,
        outputJson,
        durationMs,
        tokensUsed
      )
      .run();

    // Update agent's total tokens used
    await this.env.DB.prepare(
      `UPDATE agent_state
       SET tokens_used = tokens_used + ?
       WHERE agent_id = ?`
    )
      .bind(tokensUsed, agentId)
      .run();
  }

  /**
   * Creates an artifact in the artifacts table
   */
  private async createArtifact(
    taskId: string,
    type: string,
    name: string,
    content: string,
    metadata?: string
  ): Promise<void> {
    const artifactId = generateId('artifact');

    await this.env.DB.prepare(
      `INSERT INTO artifacts (id, task_id, type, name, content, metadata, created_at)
       VALUES (?, ?, ?, ?, ?, ?, datetime('now'))`
    )
      .bind(
        artifactId,
        taskId,
        type,
        name,
        content,
        metadata || null
      )
      .run();
  }

  /**
   * Updates agent memory with learnings from task execution
   */
  private async updateAgentMemory(
    agentId: string,
    context: SerializableContext
  ): Promise<void> {
    // Add task completion to context
    const updatedMemory: AgentMemory = {
      context: [
        ...context.memory.context.slice(-9), // Keep last 9 entries
        `Completed task: ${context.task.title}`,
      ],
      learnings: context.memory.learnings,
    };

    await this.env.DB.prepare(
      `UPDATE agent_state
       SET memory = ?, last_active = datetime('now')
       WHERE agent_id = ?`
    )
      .bind(JSON.stringify(updatedMemory), agentId)
      .run();
  }

  // ==========================================================================
  // Compute Network Operations (replaces Workers AI)
  // ==========================================================================

  /**
   * Dispatches a compute task to the distributed network and waits for result.
   * This replaces direct Workers AI calls with compute network dispatch.
   */
  private async dispatchComputeTask(
    type: 'planning' | 'execution',
    systemPrompt: string,
    prompt: string,
    maxTokens: number = 2000,
    timeout: number = 120000
  ): Promise<string | null> {
    const computeTaskId = `ctask_${Date.now().toString(36)}${Math.random().toString(36).substring(2, 8)}`;
    const now = new Date().toISOString();

    try {
      // Create compute task
      await this.env.DB
        .prepare(`
          INSERT INTO compute_tasks (
            id, type, input, config, status, priority, min_tier, created_at
          ) VALUES (?, ?, ?, ?, 'pending', 8, 'standard', ?)
        `)
        .bind(
          computeTaskId,
          type,
          JSON.stringify({ systemPrompt, prompt }),
          JSON.stringify({ maxTokens, temperature: 0.3 }),
          now
        )
        .run();

      console.log(`Created compute task ${computeTaskId} (${type})`);

      // Wait for completion
      const pollInterval = 1000;
      let elapsed = 0;

      while (elapsed < timeout) {
        const task = await this.env.DB
          .prepare('SELECT status, result, error FROM compute_tasks WHERE id = ?')
          .bind(computeTaskId)
          .first<{ status: string; result: string | null; error: string | null }>();

        if (!task) {
          throw new Error('Compute task disappeared');
        }

        if (task.status === 'completed' && task.result) {
          const result = JSON.parse(task.result);
          return result.output || null;
        }

        if (task.status === 'failed') {
          throw new Error(task.error || 'Compute task failed');
        }

        await new Promise(resolve => setTimeout(resolve, pollInterval));
        elapsed += pollInterval;
      }

      console.warn(`Compute task ${computeTaskId} timed out`);
      return null;

    } catch (error) {
      console.error(`Compute dispatch failed: ${error}`);
      return null;
    }
  }

  /**
   * Uses the compute network to plan the work for a task.
   * Falls back to a simple plan if no compute devices are available.
   */
  private async planWork(context: SerializableContext): Promise<ExecutionPlan | null> {
    try {
      const prompt = fillPromptTemplate(TASK_PLANNING_PROMPT, {
        agentRole: context.persona.role,
        agentSpecializations: context.persona.specializations.join(', '),
        taskTitle: context.task.title,
        taskDescription: context.task.description || 'No description provided',
      });

      // Check for available compute devices
      const devicesResult = await this.env.DB
        .prepare(`
          SELECT COUNT(*) as count FROM compute_devices
          WHERE status IN ('online', 'busy')
        `)
        .first<{ count: number }>();

      const hasComputeDevices = (devicesResult?.count || 0) > 0;

      if (!hasComputeDevices) {
        // No compute devices - return simple plan
        console.log('No compute devices available, using simple plan');
        return {
          steps: [
            {
              id: 'step_1',
              action: 'analyze',
              description: context.task.description || context.task.title,
              inputs: '{}',
              expectedOutput: 'Task completion',
            },
          ],
          estimatedDuration: '15 minutes',
        };
      }

      // Dispatch to compute network
      const responseText = await this.dispatchComputeTask(
        'planning',
        context.persona.system_prompt,
        prompt,
        2000
      );

      if (!responseText) {
        // Timeout or error - return default plan
        return {
          steps: [
            {
              id: 'step_1',
              action: 'analyze',
              description: context.task.description || context.task.title,
              inputs: '{}',
              expectedOutput: 'Task completion',
            },
          ],
          estimatedDuration: '15 minutes',
        };
      }

      const plan = safeParseJson<{
        steps: Array<{
          id: string;
          action: string;
          description: string;
          inputs?: string | object;
          expectedOutput: string;
        }>;
        estimatedDuration: string;
        physicalStepsIdentified?: string[];
      }>(responseText);

      if (!plan) {
        console.error('Failed to parse execution plan');
        return {
          steps: [
            {
              id: 'step_1',
              action: 'analyze',
              description: context.task.description || context.task.title,
              inputs: '{}',
              expectedOutput: 'Task completion',
            },
          ],
          estimatedDuration: '15 minutes',
        };
      }

      return {
        steps: plan.steps.map((s, i) => ({
          id: s.id || `step_${i + 1}`,
          action: s.action,
          description: s.description,
          inputs: typeof s.inputs === 'string' ? s.inputs : JSON.stringify(s.inputs || {}),
          expectedOutput: s.expectedOutput,
        })),
        estimatedDuration: plan.estimatedDuration,
      };
    } catch (error) {
      console.error('Failed to plan work:', error);
      return null;
    }
  }

  /**
   * Executes a single step using the compute network.
   */
  private async executeStep(
    planStep: PlanStep,
    context: SerializableContext
  ): Promise<StepResult> {
    const startTime = Date.now();

    try {
      const prompt = fillPromptTemplate(TASK_EXECUTION_PROMPT, {
        agentRole: context.persona.role,
        agentSpecializations: context.persona.specializations.join(', '),
        taskTitle: context.task.title,
        stepDescription: planStep.description,
        stepAction: planStep.action,
        stepInputs: planStep.inputs,
        expectedOutput: planStep.expectedOutput,
        agentMemory: context.memory.learnings.slice(-5).join('\n') || 'No previous learnings',
      });

      // Dispatch to compute network
      const responseText = await this.dispatchComputeTask(
        'execution',
        context.persona.system_prompt,
        prompt,
        4000
      );

      const durationMs = Date.now() - startTime;

      if (!responseText) {
        // Compute task failed or timed out
        return {
          success: false,
          output: JSON.stringify({ error: 'Compute task failed or timed out' }),
          needsPhysical: false,
          blockReason: 'No compute resources available',
          tokensUsed: 0,
          durationMs,
        };
      }

      const result = safeParseJson<{
        success: boolean;
        output: unknown;
        artifacts?: Array<{
          type: string;
          name: string;
          content: string;
        }>;
        needsPhysical: boolean;
        blockReason?: string;
        insights?: string[];
      }>(responseText);

      if (!result) {
        // Return raw text as output
        return {
          success: true,
          output: responseText,
          needsPhysical: false,
          blockReason: null,
          tokensUsed: estimateTokens(prompt + responseText),
          durationMs,
        };
      }

      // Check for physical barriers
      const physicalCheck = detectPhysicalBarrier(
        result.blockReason || planStep.description
      );

      return {
        success: result.success,
        output: typeof result.output === 'string' ? result.output : JSON.stringify(result.output),
        needsPhysical: result.needsPhysical || physicalCheck !== null,
        blockReason: result.blockReason || null,
        tokensUsed: estimateTokens(prompt + responseText),
        durationMs,
      };
    } catch (error) {
      console.error(`Failed to execute step ${planStep.id}:`, error);
      return {
        success: false,
        output: JSON.stringify({ error: String(error) }),
        needsPhysical: false,
        blockReason: null,
        tokensUsed: 0,
        durationMs: Date.now() - startTime,
      };
    }
  }
}

// Export the workflow class
export default WorkerWorkflow;
