"use client";

import Link from "next/link";
import {
  Sliders,
  PenTool,
  Wand2,
  Music2,
  ArrowRight,
  Sparkles,
  Layers,
  Zap
} from "lucide-react";

// Demo pages for each research technique
const demos = [
  {
    id: "voxgenesis",
    title: "Voxgenesis",
    description: "Inference script for VoxGenesis latent speaker manifold.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "voxcpm",
    title: "Voxcpm",
    description: "VoxCPM Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "style_lora",
    title: "Style Lora",
    description: "Generate Speech with Style LoRAs and DCFG (Dual Classifier-Free Guidance)",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "steering",
    title: "Steering",
    description: "Inference with Activation Steering for Training-Free Emotion Control",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "spherical",
    title: "Spherical",
    description: "Inference with Spherical Emotion Vectors (EmoSphere-TTS approach)",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "segment_aware",
    title: "Segment Aware",
    description: "Inference script for Segment-Aware Conditioning.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "prosody",
    title: "Prosody",
    description: "Controllable Voice Generation with Prosody Conditioning",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "promode",
    title: "Promode",
    description: "ProMode Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "pitchflow",
    title: "Pitchflow",
    description: "PitchFlow Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "mpe_tts",
    title: "Mpe Tts",
    description: "Inference script for MPE-TTS multi-modal emotion control.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "mismatch_aware",
    title: "Mismatch Aware",
    description: "Generate speech with mismatch-aware CFG emotion control.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "indextts2",
    title: "Indextts2",
    description: "Inference script for IndexTTS2: 8-Dimensional Emotion Vector Control",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "hed",
    title: "Hed",
    description: "Inference with Hierarchical Emotion Distribution (HED) - V6",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "facodec",
    title: "Facodec",
    description: "Generate Speech with FACodec Prosody Conditioning",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "emovoice",
    title: "Emovoice",
    description: "EmoVoice Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "emorl",
    title: "Emorl",
    description: "Generate speech with EMORL-TTS: VAD + Local Emphasis Control",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "eme_tts",
    title: "Eme Tts",
    description: "Generate speech with EME-TTS emphasis-emotion coupling.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2"
  },
  {
    id: "emoknob",
    title: "EmoKnob",
    description: "Direction vector emotion control with intensity slider",
    icon: Sliders,
    status: "ready", // ready | coming | wip
    features: ["Emotion selection", "Intensity 0-2x", "Real-time preview"],
    story: "S2" // Which story it supports
  },
  {
    id: "easv",
    title: "EASV Intensity",
    description: "Emotion-Adaptive Spherical Vectors with smooth interpolation",
    icon: Sparkles,
    status: "ready",
    features: ["Neutral-to-emotion blend", "Intensity slider", "5 emotions"],
    story: "S2"
  },
  {
    id: "emo_film",
    title: "Emo-FiLM Keyframes",
    description: "Word-level emotion control with FiLM modulation",
    icon: Layers,
    status: "coming",
    features: ["Per-word emotion", "Timeline editor", "Smooth transitions"],
    story: "S2"
  },
  {
    id: "draw_speech",
    title: "DrawSpeech",
    description: "Sketch pitch and energy curves directly",
    icon: PenTool,
    status: "coming",
    features: ["Draw pitch contour", "Draw energy", "Canvas editor"],
    story: "S2"
  },
  {
    id: "chatterbox",
    title: "Chatterbox",
    description: "Single-parameter emotion exaggeration (0=monotone, 2=dramatic)",
    icon: Wand2,
    status: "coming",
    features: ["One slider", "Paralinguistic tags", "Quick testing"],
    story: "S2"
  },
  {
    id: "maskgct",
    title: "MaskGCT Prosody",
    description: "Masked generative codec for prosody editing",
    icon: Music2,
    status: "coming",
    features: ["Prosody masking", "Selective regeneration", "Fine control"],
    story: "S2"
  }
];

export default function DemosPage() {
  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-3xl font-bold text-foreground-bright mb-2">
            Research Demos
          </h1>
          <p className="text-muted-foreground">
            Interactive demos for prosody control techniques. Each demo lets you try
            a different approach to emotion and prosody manipulation.
          </p>
        </div>

        {/* Story Context */}
        <div className="mb-8 p-4 border border-border rounded-lg bg-surface">
          <h2 className="text-sm font-medium text-foreground-bright mb-2">
            Current Focus: S2 - Temporal Keyframe Control
          </h2>
          <p className="text-sm text-muted-foreground">
            These demos explore different ways to control prosody at word-level.
            Goal: &quot;word 3 = angry, word 7 = calm&quot; with smooth transitions.
          </p>
        </div>

        {/* Demo Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {demos.map((demo) => {
            const Icon = demo.icon;
            const isReady = demo.status === "ready";

            return (
              <div
                key={demo.id}
                className={`border rounded-lg p-6 transition-all ${
                  isReady
                    ? "border-accent bg-surface hover:border-accent-bright cursor-pointer"
                    : "border-border bg-surface-raised opacity-60"
                }`}
              >
                {isReady ? (
                  <Link href={`/demos/${demo.id}`} className="block">
                    <DemoCard demo={demo} Icon={Icon} isReady={isReady} />
                  </Link>
                ) : (
                  <DemoCard demo={demo} Icon={Icon} isReady={isReady} />
                )}
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-sm text-muted-foreground">
          <p>
            Demo pages are auto-generated by research agents using Codex.
          </p>
          <p className="mt-1">
            See <code className="text-accent">.claude/commands/create-demo-page.md</code> for the template.
          </p>
        </div>
      </div>
    </div>
  );
}

function DemoCard({
  demo,
  Icon,
  isReady
}: {
  demo: typeof demos[0];
  Icon: typeof Sliders;
  isReady: boolean;
}) {
  return (
    <>
      <div className="flex items-start justify-between mb-4">
        <div className="p-2 rounded-lg bg-accent/10">
          <Icon className="w-5 h-5 text-accent" />
        </div>
        <span className={`text-xs px-2 py-1 rounded ${
          isReady
            ? "bg-green-500/10 text-green-500"
            : "bg-yellow-500/10 text-yellow-500"
        }`}>
          {isReady ? "Try it" : "Coming soon"}
        </span>
      </div>

      <h3 className="text-lg font-medium text-foreground-bright mb-2">
        {demo.title}
      </h3>

      <p className="text-sm text-muted-foreground mb-4">
        {demo.description}
      </p>

      <ul className="text-xs text-muted-foreground space-y-1 mb-4">
        {demo.features.map((feature, i) => (
          <li key={i} className="flex items-center gap-2">
            <span className="w-1 h-1 rounded-full bg-accent" />
            {feature}
          </li>
        ))}
      </ul>

      {isReady && (
        <div className="flex items-center text-sm text-accent">
          Open demo <ArrowRight className="w-4 h-4 ml-1" />
        </div>
      )}
    </>
  );
}
