"use client";

import Link from "next/link";
import { ChevronRight, Beaker } from "lucide-react";
import { DEMOS, LAB_REFS } from "@/lib/demos";
import { DemoCard } from "@/components/demos/DemoCard";

export default function DemosPage() {
  // Group demos by lab for clear organization
  const demosByLab = DEMOS.reduce(
    (acc, demo) => {
      const key = demo.labSlug;
      if (!acc[key]) acc[key] = [];
      acc[key].push(demo);
      return acc;
    },
    {} as Record<string, typeof DEMOS>
  );

  return (
    <div className="min-h-screen bg-background px-4 sm:px-8 py-6 sm:py-8">
      <div className="max-w-6xl mx-auto">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-1.5 text-sm text-foreground-muted mb-6">
          <Link
            href="/explore"
            className="hover:text-foreground transition-colors min-h-[44px] flex items-center"
          >
            Explore
          </Link>
          <ChevronRight className="w-3.5 h-3.5 text-foreground-subtle" />
          <span className="text-foreground-bright">Research Demos</span>
        </nav>

        {/* Header */}
        <div className="mb-8 sm:mb-10">
          <h1 className="text-2xl sm:text-3xl font-semibold text-foreground-bright mb-2">
            Research Demos
          </h1>
          <p className="text-sm text-foreground-muted max-w-2xl">
            Interactive demos for prosody control techniques. Each demo lets you
            try a different approach to emotion and prosody manipulation.
          </p>
        </div>

        {/* Demos grouped by lab */}
        {Object.entries(demosByLab).map(([labSlug, demos]) => {
          const labRef = LAB_REFS[labSlug];

          return (
            <section key={labSlug} className="mb-10 last:mb-0">
              {/* Lab section header */}
              {labRef && (
                <div className="flex items-center justify-between mb-4">
                  <Link
                    href={labRef.path}
                    className="group flex items-center gap-2 min-h-[44px]"
                  >
                    <Beaker className="w-4 h-4 text-foreground-subtle group-hover:text-foreground-muted transition-colors" />
                    <span className="text-sm font-medium text-foreground group-hover:text-foreground-bright transition-colors">
                      {labRef.name}
                    </span>
                    <ChevronRight className="w-3.5 h-3.5 text-foreground-subtle group-hover:text-foreground-muted transition-colors" />
                  </Link>
                  <span className="text-xs text-foreground-subtle">
                    {demos.filter((d) => d.status === "ready").length} ready
                  </span>
                </div>
              )}

              {/* Demo grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {demos.map((demo) => (
                  <DemoCard
                    key={demo.id}
                    demo={demo}
                    showLabLink={false}
                  />
                ))}
              </div>
            </section>
          );
        })}

        {/* Footer */}
        <div className="mt-10 pt-6 border-t border-border text-center text-xs text-foreground-subtle">
          <p>
            Demo pages are auto-generated by research agents using Codex.
          </p>
        </div>
      </div>
    </div>
  );
}
