"use client";

/**
 * DemoCard - Reusable card for displaying a research demo.
 *
 * Used on:
 * - Lab overview page (compact variant)
 * - Demos listing page (full variant)
 */

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Demo } from "@/lib/demos";

interface DemoCardProps {
  demo: Demo;
  /** Compact mode hides features list (used in lab overview) */
  compact?: boolean;
  /** Show lab context link (used on demos listing) */
  showLabLink?: boolean;
  labName?: string;
  labPath?: string;
}

export function DemoCard({
  demo,
  compact = false,
  showLabLink = false,
  labName,
  labPath,
}: DemoCardProps) {
  const Icon = demo.icon;
  const isReady = demo.status === "ready";

  const content = (
    <div
      className={cn(
        "rounded-lg border p-4 sm:p-5 transition-all h-full",
        isReady
          ? "border-border hover:border-foreground-muted/60 bg-background-elevated cursor-pointer"
          : "border-border bg-background-elevated opacity-60"
      )}
    >
      {/* Top row: icon + status badge */}
      <div className="flex items-start justify-between mb-3">
        <div className="p-2 rounded-lg bg-foreground/5">
          <Icon className="w-4 h-4 text-foreground-bright" />
        </div>
        <span
          className={cn(
            "text-[11px] px-2 py-0.5 rounded-full font-medium",
            isReady
              ? "bg-green-500/10 text-green-400"
              : "bg-foreground-muted/10 text-foreground-muted"
          )}
        >
          {isReady ? "Ready" : "Coming soon"}
        </span>
      </div>

      {/* Title */}
      <h3 className="text-sm font-medium text-foreground-bright mb-1.5 leading-tight">
        {demo.title}
      </h3>

      {/* Description */}
      <p
        className={cn(
          "text-xs text-foreground-muted leading-relaxed",
          compact ? "line-clamp-2" : "line-clamp-3 mb-3"
        )}
      >
        {demo.description}
      </p>

      {/* Features (full mode only) */}
      {!compact && demo.features.length > 0 && (
        <ul className="text-[11px] text-foreground-subtle space-y-1 mb-3">
          {demo.features
            .filter((f) => f !== "Generated by frontend-designer")
            .map((feature, i) => (
              <li key={i} className="flex items-center gap-1.5">
                <span className="w-1 h-1 rounded-full bg-foreground-muted/50 flex-shrink-0" />
                {feature}
              </li>
            ))}
        </ul>
      )}

      {/* Lab context (demos listing only) */}
      {showLabLink && labName && labPath && (
        <div className="mt-2 pt-2 border-t border-border/50">
          <Link
            href={labPath}
            onClick={(e) => e.stopPropagation()}
            className="text-[11px] text-foreground-subtle hover:text-foreground-muted transition-colors"
          >
            {labName}
          </Link>
        </div>
      )}

      {/* CTA */}
      {isReady && (
        <div className="flex items-center text-xs text-foreground-muted mt-2 group-hover:text-foreground-bright transition-colors">
          Try it <ArrowRight className="w-3 h-3 ml-1" />
        </div>
      )}
    </div>
  );

  if (isReady) {
    return (
      <Link href={`/demos/${demo.id}`} className="group block h-full">
        {content}
      </Link>
    );
  }

  return content;
}
