/**
 * Speculative Decoding Protocol
 *
 * Implements speculative decoding for distributed inference:
 * 1. Small models (phones/browsers) generate draft tokens
 * 2. Large models (GPUs) verify drafts in parallel
 * 3. Accepted tokens are kept, rejected tokens trigger recompute
 * 4. Achieves ~3x speedup through parallel speculation + verification
 */

/**
 * Draft token with confidence score
 */
export interface DraftToken {
  /** Token ID */
  tokenId: number;
  /** Token text */
  text: string;
  /** Log probability from draft model */
  logProb: number;
  /** Confidence score (0-1) */
  confidence: number;
  /** Position in sequence */
  position: number;
}

/**
 * Draft sequence generated by small model
 */
export interface DraftSequence {
  /** Unique draft ID */
  draftId: string;
  /** Draft tokens */
  tokens: DraftToken[];
  /** Context/prompt used */
  context: string;
  /** Draft model ID */
  modelId: string;
  /** Generation timestamp */
  generatedAt: string;
  /** Device ID that generated draft */
  deviceId: string;
  /** Average confidence across tokens */
  avgConfidence: number;
}

/**
 * Verification result for a single token
 */
export interface TokenVerification {
  /** Token position */
  position: number;
  /** Whether token was accepted */
  accepted: boolean;
  /** Log probability from verify model */
  verifyLogProb: number;
  /** Log probability from draft model */
  draftLogProb: number;
  /** Probability ratio (verify / draft) */
  probRatio: number;
  /** Replacement token if rejected */
  replacementToken?: DraftToken;
}

/**
 * Complete verification result
 */
export interface VerificationResult {
  /** Unique verification ID */
  verificationId: string;
  /** Original draft ID */
  draftId: string;
  /** Token-level verification results */
  tokenResults: TokenVerification[];
  /** Number of accepted tokens */
  acceptedCount: number;
  /** Acceptance rate (0-1) */
  acceptanceRate: number;
  /** Final token sequence (accepted + replacement) */
  finalTokens: DraftToken[];
  /** Final text output */
  finalText: string;
  /** Verification timestamp */
  verifiedAt: string;
  /** Device ID that verified */
  deviceId: string;
  /** Speedup achieved vs sequential (estimated) */
  speedupFactor: number;
}

/**
 * Speculative decoding task
 */
export interface SpeculativeTask {
  /** Task ID */
  taskId: string;
  /** Task type (draft_generation or draft_verification) */
  type: "draft_generation" | "draft_verification";
  /** Context/prompt */
  context: string;
  /** Draft to verify (for verification tasks) */
  draft?: DraftSequence;
  /** Configuration */
  config: {
    /** Number of draft tokens to generate */
    draftCount: number;
    /** Acceptance threshold (typically 0.8-1.0) */
    acceptanceThreshold: number;
    /** Draft model ID */
    draftModelId: string;
    /** Verification model ID */
    verifyModelId: string;
    /** Temperature for sampling */
    temperature: number;
  };
}

/**
 * Speculative decoding statistics
 */
export interface SpeculativeStats {
  /** Total drafts generated */
  totalDrafts: number;
  /** Total drafts verified */
  totalVerified: number;
  /** Average acceptance rate */
  avgAcceptanceRate: number;
  /** Average speedup factor */
  avgSpeedupFactor: number;
  /** Total tokens generated */
  totalTokens: number;
  /** Total tokens accepted */
  totalAccepted: number;
  /** Total compute time saved (ms) */
  timeSaved: number;
}

/**
 * Generate unique draft ID
 */
export function generateDraftId(): string {
  return `draft_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Generate unique verification ID
 */
export function generateVerificationId(): string {
  return `verify_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Calculate acceptance based on probability ratio
 *
 * Token is accepted if: P_verify(token) / P_draft(token) >= threshold
 */
export function shouldAcceptToken(
  verifyLogProb: number,
  draftLogProb: number,
  threshold: number
): boolean {
  // Convert log probs to probs
  const verifyProb = Math.exp(verifyLogProb);
  const draftProb = Math.exp(draftLogProb);

  // Calculate ratio
  const ratio = verifyProb / Math.max(draftProb, 1e-10); // Avoid division by zero

  return ratio >= threshold;
}

/**
 * Calculate average confidence for draft sequence
 */
export function calculateAvgConfidence(tokens: DraftToken[]): number {
  if (tokens.length === 0) return 0;
  const sum = tokens.reduce((acc, token) => acc + token.confidence, 0);
  return sum / tokens.length;
}

/**
 * Calculate speedup factor
 *
 * Speedup = (K + 1) / (1 + R)
 * where K = draft tokens, R = rejection count
 */
export function calculateSpeedupFactor(
  draftCount: number,
  acceptedCount: number
): number {
  const rejectionCount = draftCount - acceptedCount;
  const speedup = (draftCount + 1) / (1 + rejectionCount);
  return Math.max(1.0, speedup); // Minimum 1x speedup
}

/**
 * Estimate time saved by speculative decoding
 *
 * @param draftCount Number of draft tokens
 * @param acceptedCount Number of accepted tokens
 * @param sequentialTimePerToken Time for sequential generation (ms)
 * @param draftTime Total draft generation time (ms)
 * @param verifyTime Total verification time (ms)
 * @returns Estimated time saved in ms
 */
export function estimateTimeSaved(
  draftCount: number,
  acceptedCount: number,
  sequentialTimePerToken: number,
  draftTime: number,
  verifyTime: number
): number {
  // Sequential time = time per token * number of tokens
  const sequentialTime = sequentialTimePerToken * acceptedCount;

  // Speculative time = draft time + verify time (parallel)
  const speculativeTime = draftTime + verifyTime;

  return Math.max(0, sequentialTime - speculativeTime);
}

/**
 * Batch multiple drafts for efficient verification
 */
export function batchDrafts(
  drafts: DraftSequence[],
  maxBatchSize: number
): DraftSequence[][] {
  const batches: DraftSequence[][] = [];

  for (let i = 0; i < drafts.length; i += maxBatchSize) {
    batches.push(drafts.slice(i, i + maxBatchSize));
  }

  return batches;
}

/**
 * Validate draft sequence
 */
export function validateDraft(draft: DraftSequence): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!draft.draftId) {
    errors.push("Missing draft ID");
  }

  if (!draft.tokens || draft.tokens.length === 0) {
    errors.push("No tokens in draft");
  }

  if (draft.tokens) {
    draft.tokens.forEach((token, idx) => {
      if (token.position !== idx) {
        errors.push(`Token position mismatch at index ${idx}`);
      }
      if (token.confidence < 0 || token.confidence > 1) {
        errors.push(`Invalid confidence at position ${idx}: ${token.confidence}`);
      }
    });
  }

  if (!draft.context) {
    errors.push("Missing context");
  }

  if (!draft.modelId) {
    errors.push("Missing model ID");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Merge accepted tokens and replacements into final sequence
 */
export function mergeFinalSequence(
  tokenResults: TokenVerification[],
  originalDraft: DraftToken[]
): DraftToken[] {
  const finalTokens: DraftToken[] = [];

  for (const result of tokenResults) {
    if (result.accepted) {
      finalTokens.push(originalDraft[result.position]);
    } else if (result.replacementToken) {
      finalTokens.push(result.replacementToken);
    }
    // If rejected and no replacement, stop here (truncate)
    else {
      break;
    }
  }

  return finalTokens;
}

/**
 * Convert token sequence to text
 */
export function tokensToText(tokens: DraftToken[]): string {
  return tokens.map((t) => t.text).join("");
}

/**
 * Default speculative decoding configuration
 */
export const DEFAULT_SPECULATIVE_CONFIG = {
  draftCount: 8, // Generate 8 draft tokens
  acceptanceThreshold: 0.8, // Accept if verify_prob / draft_prob >= 0.8
  batchSize: 4, // Verify up to 4 drafts in parallel
  temperature: 0.8, // Slightly higher temp for diversity
} as const;
