/**
 * Shared demos data module
 *
 * Single source of truth for all research demos.
 * Each demo is associated with a parent lab via labSlug/labOwner.
 */

import {
  Sliders,
  Sparkles,
  Layers,
  PenTool,
  Wand2,
  Music2,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface Demo {
  /** Unique demo ID, matches the route segment under /demos/ */
  id: string;
  /** Display title */
  title: string;
  /** Short description of the technique */
  description: string;
  /** Lucide icon component */
  icon: LucideIcon;
  /** Readiness status */
  status: "ready" | "coming" | "wip";
  /** Feature bullet points */
  features: string[];
  /** Story reference (research sprint) */
  story: string;
  /** Parent lab slug (matches lab.slug) */
  labSlug: string;
  /** Parent lab owner username (matches lab.owner.username) */
  labOwner: string;
}

/**
 * Lab metadata for display in demo pages.
 * Maps labSlug to lab display info.
 */
export interface LabRef {
  slug: string;
  owner: string;
  name: string;
  path: string;
}

/** Known lab references for demo-to-lab linking */
export const LAB_REFS: Record<string, LabRef> = {
  "emotion-tts": {
    slug: "emotion-tts",
    owner: "labfork",
    name: "Emotion TTS Research",
    path: "/labs/labfork/emotion-tts",
  },
};

/**
 * All research demos.
 * Every demo belongs to a parent lab via labSlug + labOwner.
 */
export const DEMOS: Demo[] = [
  {
    id: "voxgenesis",
    title: "VoxGenesis",
    description: "Inference script for VoxGenesis latent speaker manifold.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "voxcpm",
    title: "VoxCPM",
    description: "VoxCPM Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "style_lora",
    title: "Style LoRA",
    description:
      "Generate Speech with Style LoRAs and DCFG (Dual Classifier-Free Guidance)",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "steering",
    title: "Steering",
    description:
      "Inference with Activation Steering for Training-Free Emotion Control",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "spherical",
    title: "Spherical",
    description:
      "Inference with Spherical Emotion Vectors (EmoSphere-TTS approach)",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "segment_aware",
    title: "Segment Aware",
    description: "Inference script for Segment-Aware Conditioning.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "prosody",
    title: "Prosody",
    description: "Controllable Voice Generation with Prosody Conditioning",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "promode",
    title: "ProMode",
    description: "ProMode Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "pitchflow",
    title: "PitchFlow",
    description: "PitchFlow Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "mpe_tts",
    title: "MPE-TTS",
    description:
      "Inference script for MPE-TTS multi-modal emotion control.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "mismatch_aware",
    title: "Mismatch Aware",
    description: "Generate speech with mismatch-aware CFG emotion control.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "indextts2",
    title: "IndexTTS2",
    description:
      "Inference script for IndexTTS2: 8-Dimensional Emotion Vector Control",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "hed",
    title: "HED",
    description:
      "Inference with Hierarchical Emotion Distribution (HED) - V6",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "facodec",
    title: "FACodec",
    description: "Generate Speech with FACodec Prosody Conditioning",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "emovoice",
    title: "EmoVoice",
    description: "EmoVoice Inference Script",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "emorl",
    title: "EmoRL",
    description: "Generate speech with EMORL-TTS: VAD + Local Emphasis Control",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "eme_tts",
    title: "EME-TTS",
    description: "Generate speech with EME-TTS emphasis-emotion coupling.",
    icon: Zap,
    status: "ready",
    features: ["Generated by frontend-designer"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "emoknob",
    title: "EmoKnob",
    description: "Direction vector emotion control with intensity slider",
    icon: Sliders,
    status: "ready",
    features: ["Emotion selection", "Intensity 0-2x", "Real-time preview"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "easv",
    title: "EASV Intensity",
    description:
      "Emotion-Adaptive Spherical Vectors with smooth interpolation",
    icon: Sparkles,
    status: "ready",
    features: ["Neutral-to-emotion blend", "Intensity slider", "5 emotions"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "emo_film",
    title: "Emo-FiLM Keyframes",
    description: "Word-level emotion control with FiLM modulation",
    icon: Layers,
    status: "coming",
    features: ["Per-word emotion", "Timeline editor", "Smooth transitions"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "draw_speech",
    title: "DrawSpeech",
    description: "Sketch pitch and energy curves directly",
    icon: PenTool,
    status: "coming",
    features: ["Draw pitch contour", "Draw energy", "Canvas editor"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "chatterbox",
    title: "Chatterbox",
    description:
      "Single-parameter emotion exaggeration (0=monotone, 2=dramatic)",
    icon: Wand2,
    status: "coming",
    features: ["One slider", "Paralinguistic tags", "Quick testing"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
  {
    id: "maskgct",
    title: "MaskGCT Prosody",
    description: "Masked generative codec for prosody editing",
    icon: Music2,
    status: "coming",
    features: ["Prosody masking", "Selective regeneration", "Fine control"],
    story: "S2",
    labSlug: "emotion-tts",
    labOwner: "labfork",
  },
];

/**
 * Get demos for a specific lab by slug.
 */
export function getDemosForLab(labSlug: string): Demo[] {
  return DEMOS.filter((d) => d.labSlug === labSlug);
}

/**
 * Get a single demo by ID.
 */
export function getDemoById(id: string): Demo | undefined {
  return DEMOS.find((d) => d.id === id);
}

/**
 * Get the lab reference for a demo.
 */
export function getLabRefForDemo(demo: Demo): LabRef | undefined {
  return LAB_REFS[demo.labSlug];
}

/**
 * Get the count of ready demos for a lab.
 */
export function getReadyDemoCount(labSlug: string): number {
  return getDemosForLab(labSlug).filter((d) => d.status === "ready").length;
}
